use kurs;

insert into Vuz values (1, "РЭУ им. Плеханова", "any,msk,spb");
insert into Vuz values (2, "ВШЭ", "any,msk,spb");
insert into Vuz values (3, "МГИМО","any,msk");
insert into Vuz values (4, "СПГМУ","any,spb,nvs");
insert into Vuz values (5, "СГУ им. Чернышевского","any,sam");
insert into Vuz values (6, "МГУ","any,msk,zel");
insert into Vuz values (7, "Академия народного хозяйства","any,nvs,zel");

insert into Napravl values (1, "Инфобез", 240, 'inf|eco',1);
insert into Napravl values (2,"Мэнеджмент",210,'man',1);
insert into Napravl values (3,"Мэнеджмент",215,'man',2);
insert into Napravl values (4,"Мэнеджмент",235,'man',3);
insert into Napravl values (5,"ГРТСИ",190,'',1);
insert into Napravl values (6,"IT-менеджмент",300,'inf|man',3);
insert into Napravl values (7,"Медицинский",330,'med',4);
insert into Napravl values (8,"Биотех",310,'inf|med',4);
insert into Napravl values (9,"Страноведение и туризм",205,'',5);
insert into Napravl values (10,"Филология",230,'',5);
insert into Napravl values (11,"Филология",260,'',6);
insert into Napravl values (12,"Кибертех",320,'ing|inf',6);
insert into Napravl values (13,"Инженерия в конструктировании",290,'ing',5);
insert into Napravl values (14,"Международный туризм",235,'',7);

insert into EGE values (1,"rus");
insert into EGE values (1,"mat");
insert into EGE values (1,"inf");
insert into EGE values (2,"rus");
insert into EGE values (2,"mat");
insert into EGE values (2,"obs");
insert into EGE values (3,"rus");
insert into EGE values (3,"mat");
insert into EGE values (3,"obs");
insert into EGE values (4,"rus");
insert into EGE values (4,"mat");
insert into EGE values (4,"obs");
insert into EGE values (5,"rus");
insert into EGE values (5,"mat");
insert into EGE values (5,"obs");
insert into EGE values (6,"rus");
insert into EGE values (6,"mat");
insert into EGE values (6,"inf");
insert into EGE values (6,"obs");
insert into EGE values (7,"rus");
insert into EGE values (7,"mat");
insert into EGE values (7,"bio");
insert into EGE values (7,"him");
insert into EGE values (8,"rus");
insert into EGE values (8,"mat");
insert into EGE values (8,"bio");
insert into EGE values (8,"inf");
insert into EGE values (9,"rus");
insert into EGE values (9,"geo");
insert into EGE values (9,"obs");
insert into EGE values (9,"rus");
insert into EGE values (9,"geo");
insert into EGE values (10,"rus");
insert into EGE values (10,"lit");
insert into EGE values (10,"obs");
insert into EGE values (11,"rus");
insert into EGE values (11,"lit");
insert into EGE values (11,"obs");
insert into EGE values (12,"inf");
insert into EGE values (12,"rus");
insert into EGE values (12,"mat");
insert into EGE values (12,"fiz");
insert into EGE values (13,"rus");
insert into EGE values (13,"mat");
insert into EGE values (13,"fiz");
insert into EGE values (14,"rus");
insert into EGE values (14,"geo");
insert into EGE values (14,"obs");

